v2.1 docs Updated
traderjoe-xyz/joe-docs-v2 pull request #27
Opened 2023-03-21 11:09 UTC by 0xTeuteu

Updated the v2 doc to fit the v2.1 changes

2023-03-21 17:42 UTC, pecio222 requested changes
Guides need complete revamp - v2.1 introduces changes in swap function arguments + structs, so examples will not compile

2023-03-21 17:42 UTC, pecio222 commented on docs/guides/implement-a-swap.md
>  uint256 amountOutReal = router.swapExactTokensForTokens(amountIn, amountOutWithSlippage, pairBinSteps, tokenPath, receiverAddress, block.timestamp);
this will not compile - arguments in all swap functions changed, needs revamp

2023-03-21 17:42 UTC, pecio222 commented on docs/DecodeExamples.md
> +Some of the new output variables from `functions` and `event` of the new `v2.1 Dex` needs to be decoded. Here are some propositons in order to do so: <br/>
propositions

2023-03-21 17:42 UTC, pecio222 commented on docs/DecodeExamples.md
> +### Decode `amountsOut` from the `swap` function
from the `swap` event

2023-03-21 17:42 UTC, pecio222 commented on docs/DecodeExamples.md
> +    """
might be good idea to add `amounts = bytes.fromhex(amounts)` here so it works directly with string copied from snowtrace

2023-03-21 17:42 UTC, pecio222 commented on docs/DecodeExamples.md
> +    """
might be good idea to add amounts = bytes.fromhex(amounts) here so it works directly with string copied from snowtrace

2023-03-31 00:46 UTC, cryptofish7 requested changes

2023-04-02 18:55 UTC, closed without merging